COMMAND_SIZE = 9
INT_SIZE = 8
LIST_SIZE = 12
HIT_OP = "hit      "
PAS_OP = "pas      "
FLD_OP = "fld      "
BYE_OP = "bye      "
DIST_OP = "distrib  "
OK_OP = "okay     "
CON_OP = "conn     "
HAND_OP = "hand     "
NAME_OP = "name     "
STOP_SERVER_OP = "stop    "
